% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{tcolorbox}
\usepackage{listings}
\lstset{ breaklines=true, breakatwhitespace=true, keepspaces=true, xleftmargin=0pt, xrightmargin=0pt, frame=single, columns=fullflexible, linewidth=\dimexpr\textwidth+1in\relax }
\usepackage[none]{hyphenat}
\usepackage[dvipsnames]{xcolor}
\sloppy
\AtBeginDocument{\geometry{a4paper, top=1in, bottom=1.5in, left=0.75in, right=0.75in}}
\AtBeginDocument{\setlength{\textwidth}{6.5in}}
\linespread{1.2}
\usepackage[hidelinks]{hyperref} % Assure des liens actifs mais discrets
\hypersetup{colorlinks=true, linkcolor=blue, urlcolor=blue, filecolor=blue, citecolor=blue}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{fontspec}
\setmainfont{Cambria}
\renewcommand{\normalsize}{\fontsize{12}{14}\selectfont}
\setsansfont{Franklin Gothic Demi Cond}
\setmonofont{Courier New}
\usepackage{titlesec}
\titleformat{\section}{\Huge\bfseries\color{blue}}{\thesection}{1em}{}
\titleformat{\subsection}{\huge\bfseries\color{blue}}{\thesubsection}{1em}{}
\titleformat{\subsubsection}{\LARGE\bfseries\color{blue}}{\thesubsubsection}{1em}{}
\usepackage{tocloft}
\usepackage{xcolor}
\usepackage{fontspec}
\definecolor{sectioncolor}{RGB}{40, 58, 129}
\definecolor{subsectioncolor}{RGB}{72, 101, 160}
\definecolor{subsubsectioncolor}{RGB}{106, 137, 188}
\setlength{\cftbeforesecskip}{5pt}
\setlength{\cftbeforesubsecskip}{3pt}
\setlength{\cftbeforesubsubsecskip}{2pt}
\cftsetindents{section}{0em}{3em}
\cftsetindents{subsection}{1.5em}{3.5em}
\cftsetindents{subsubsection}{3em}{4em}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}

\begin{document}

\begin{titlepage}
    \begin{center}
        \sffamily 
        {\Large \textbf{RÉPUBLIQUE DU SÉNÉGAL}}\\[0.3cm]
        \includegraphics[width=3cm]{../Donnees/LOGO3.jpg} \\[0.3cm]
        
        {\large \textbf{Un Peuple - Un But - Une Foi}}\\[0.5cm]
        
        {\Large \textbf{Ministère de l'Économie, du Plan et de la Coopération}}\\[0.5cm]
        
        \includegraphics[width=3cm]{../Donnees/LOGO2.jpg} \\[0.3cm]
        
        {\Large \textbf{Agence Nationale de la Statistique et de la Démographie (ANSD)}}\\[0.5cm]
        
        \includegraphics[width=3cm]{../Donnees/LOGO1.jpg} \\[0.3cm]
        
        {\LARGE \textbf{École Nationale de la Statistique et de l'Analyse Économique (ENSAE | Pierre Ndiaye)}}\\[0.8cm]
        
        \textbf{\Huge \color{blue} TP9: Merge des bases welfare 2018 et 2021}\\[0.6cm]
        \rule{\linewidth}{0.6mm} \\[1cm]
        
        \vfill  
        
        \begin{minipage}{0.5\textwidth}
    \begin{flushleft} \large
        \emph{\textsf{Rédigé par :}}\\
        \textbf{FOGWOUNG DJOUFACK Sarah-Laure}\\
        \textbf{NIASS Ahmadou}\\
        \textbf{NGUEMFOUO NGOUMTSA Célina}\\
        \textbf{SENE Malick}\\
        \textit{Élèves Ingénieurs Statisticiens Économistes}
    \end{flushleft}
\end{minipage}
        \hfill
        \begin{minipage}{0.4\textwidth}
            \begin{flushright} \large
                \emph{\textsf{Sous la supervision de :}} \\
                \textbf{M. Aboubacar HEMA}\\
                \textit{Research Analyst }
            \end{flushright}
        \end{minipage}

        \vfill

        {\large \textsf{Année scolaire : 2024/2025}}\\[0.5cm]
        
    \end{center}
\end{titlepage}

\phantomsection
\tableofcontents

\newpage

\hypertarget{consigne-du-tp4}{%
\section{CONSIGNE DU TP4}\label{consigne-du-tp4}}

L'objectif de ce TP est de fusionner les bases de données welfare 2018
et welfare 2021 en assurant une harmonisation et vérification rigoureuse
des correspondances des labels entre les deux bases.

\newpage

\hypertarget{execution-du-travail-uxe0-faire}{%
\section{Execution du travail à
faire}\label{execution-du-travail-uxe0-faire}}

\hypertarget{importation-et-chargement-des-packages}{%
\subsection{1- Importation et chargement des
packages}\label{importation-et-chargement-des-packages}}

Dans cette étape, nous allons vérifier si les packages nécessaires sont
installés, les installer si besoin, puis les charger. Pour charger un
package, nous utilisons la fonction library() du package utils.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Liste des packages nécessaires }
\NormalTok{packages }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"readr"}\NormalTok{, }\StringTok{"haven"}\NormalTok{, }
              \StringTok{"utils"}\NormalTok{, }\StringTok{"dplyr"}\NormalTok{, }\StringTok{"gtsummary"}\NormalTok{, }\StringTok{"labelled"}\NormalTok{)}

\CommentTok{\# Fonction pour vérifier et installer un package manquant}
\NormalTok{installer\_si\_manquant }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(package) \{}
  \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(package, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{)) \{}
    \FunctionTok{install.packages}\NormalTok{(package, }\AttributeTok{dependencies =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  \}}
  \CommentTok{\# Chargement du package avec library() du package utils}
  \FunctionTok{library}\NormalTok{(package, }\AttributeTok{character.only =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{\}}

\CommentTok{\# Appliquer la fonction à tous les packages listés}
\FunctionTok{lapply}\NormalTok{(packages, installer\_si\_manquant)}
\end{Highlighting}
\end{Shaded}

\hypertarget{importation-des-bases-de-donnuxe9es}{%
\subsection{2- Importation des bases de
données}\label{importation-des-bases-de-donnuxe9es}}

Dans cette étape, nous allons importer les bases de données welfare de
2018 et 2021.Pour cela, nous utilisons la fonction read\_dta du package
haven.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Chargement de la base de données 2018}
\NormalTok{welfare\_2018 }\OtherTok{\textless{}{-}}\NormalTok{ haven}\SpecialCharTok{::}\FunctionTok{read\_dta}\NormalTok{(}
  \StringTok{"../Donnees/ehcvm\_welfare\_sen2018.dta"}\NormalTok{)}

\CommentTok{\# Chargement de la base de données 2021}
\NormalTok{welfare\_2021 }\OtherTok{\textless{}{-}}\NormalTok{ haven}\SpecialCharTok{::}\FunctionTok{read\_dta}\NormalTok{(}
  \StringTok{"../Donnees/ehcvm\_welfare\_sen2021.dta"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{exploration-des-donnuxe9es}{%
\subsection{3- Exploration des
données}\label{exploration-des-donnuxe9es}}

Dans cette étape, nous allons explorer les données en affichant un
aperçu des premières lignes et les dimensions des bases.

\hypertarget{aperuxe7u-des-premieres-lignes-des-bases-de-donnuxe9es}{%
\subsubsection{Aperçu des premieres lignes des bases de
données}\label{aperuxe7u-des-premieres-lignes-des-bases-de-donnuxe9es}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Affichage des premières lignes de chaque base}
\FunctionTok{head}\NormalTok{(welfare\_2018)}
\FunctionTok{head}\NormalTok{(welfare\_2021)}
\end{Highlighting}
\end{Shaded}

\hypertarget{dimension-des-bases}{%
\subsubsection{Dimension des bases}\label{dimension-des-bases}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Vérifier le nombre de lignes et de colonnes pour chaque base}

\NormalTok{dim\_2018 }\OtherTok{\textless{}{-}} \FunctionTok{dim}\NormalTok{(welfare\_2018)}
\NormalTok{dim\_2021 }\OtherTok{\textless{}{-}} \FunctionTok{dim}\NormalTok{(welfare\_2021)}
\NormalTok{dim\_2018}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7156   35
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dim\_2021}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7120   47
\end{verbatim}

On remarque ici que la base welfare de 2018 a porté sur 7156 individus
et il y avait 35 variables tandis que pour celle de 2021 il y avait 7120
individus et elle portait sur 47 variables.

\hypertarget{structure-des-variables}{%
\subsubsection{Structure des variables}\label{structure-des-variables}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Vérifier la structure et le type des variables}

\FunctionTok{glimpse}\NormalTok{(welfare\_2018)}
\FunctionTok{glimpse}\NormalTok{(welfare\_2021)}
\end{Highlighting}
\end{Shaded}

\hypertarget{comparaison-des-variables-entre-les-deux-bases}{%
\subsection{4- Comparaison des variables entre les deux
bases}\label{comparaison-des-variables-entre-les-deux-bases}}

Dans cette étape, nous allons identifier les variables communes aux deux
bases et vérifier que leurs types et labels sont identiques ou pas.

\hypertarget{identification-des-variables-communes-aux-deux-bases.}{%
\subsubsection{Identification des variables communes aux deux
bases.}\label{identification-des-variables-communes-aux-deux-bases.}}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Lister toutes les variables des deux bases}
\NormalTok{vars\_2018 }\OtherTok{\textless{}{-}} \FunctionTok{colnames}\NormalTok{(welfare\_2018)}
\NormalTok{vars\_2021 }\OtherTok{\textless{}{-}} \FunctionTok{colnames}\NormalTok{(welfare\_2021)}
\CommentTok{\# Identification des variables communes}
\NormalTok{vars\_communes }\OtherTok{\textless{}{-}} \FunctionTok{intersect}\NormalTok{(vars\_2018, vars\_2021)}
\FunctionTok{print}\NormalTok{(vars\_communes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "country"   "year"      "hhid"      "grappe"    "menage"    "vague"    
##  [7] "zae"       "region"    "milieu"    "hhweight"  "hhsize"    "eqadu1"   
## [13] "eqadu2"    "hgender"   "hage"      "hmstat"    "hreligion" "hnation"  
## [19] "heduc"     "hdiploma"  "hhandig"   "hactiv7j"  "hactiv12m" "hbranch"  
## [25] "hsectins"  "hcsp"      "dali"      "dnal"      "dtot"      "pcexp"    
## [31] "zzae"      "zref"      "def_spa"   "def_temp"
\end{verbatim}

Il y a 34 variables communes aux deux bases.

\hypertarget{regardons-si-ces-variables-sont-de-meme-type-pour-les-deux-bases.}{%
\subsubsection{Regardons si ces variables sont de meme type pour les
deux
bases.}\label{regardons-si-ces-variables-sont-de-meme-type-pour-les-deux-bases.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Comparaison des types des variables communes dans les deux bases}
\NormalTok{types\_communes\_2018 }\OtherTok{\textless{}{-}} \FunctionTok{vapply}\NormalTok{(welfare\_2018[vars\_communes], }
                              \ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{paste}\NormalTok{(}\FunctionTok{class}\NormalTok{(x), }
                              \AttributeTok{collapse =} \StringTok{" "}\NormalTok{), }\FunctionTok{character}\NormalTok{(}\DecValTok{1}\NormalTok{))}
\NormalTok{types\_communes\_2021 }\OtherTok{\textless{}{-}} \FunctionTok{vapply}\NormalTok{(welfare\_2021[vars\_communes], }
                              \ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{paste}\NormalTok{(}\FunctionTok{class}\NormalTok{(x), }
                              \AttributeTok{collapse =} \StringTok{" "}\NormalTok{), }\FunctionTok{character}\NormalTok{(}\DecValTok{1}\NormalTok{))}

\CommentTok{\# Création du tableau de comparaison}
\NormalTok{comparaison }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Variable =}\NormalTok{ vars\_communes,}
  \AttributeTok{Type\_2018 =}\NormalTok{ types\_communes\_2018,}
  \AttributeTok{Type\_2021 =}\NormalTok{ types\_communes\_2021,}
  \AttributeTok{Same\_Type =}\NormalTok{ types\_communes\_2018 }\SpecialCharTok{==}\NormalTok{ types\_communes\_2021}
\NormalTok{)}

\CommentTok{\# Affichage du résultat}
\FunctionTok{print}\NormalTok{(comparaison)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            Variable                        Type_2018
## country     country                        character
## year           year                          numeric
## hhid           hhid                          numeric
## grappe       grappe                          numeric
## menage       menage                          numeric
## vague         vague                          numeric
## zae             zae                          numeric
## region       region haven_labelled vctrs_vctr double
## milieu       milieu haven_labelled vctrs_vctr double
## hhweight   hhweight                          numeric
## hhsize       hhsize                          numeric
## eqadu1       eqadu1                          numeric
## eqadu2       eqadu2                          numeric
## hgender     hgender haven_labelled vctrs_vctr double
## hage           hage                          numeric
## hmstat       hmstat haven_labelled vctrs_vctr double
## hreligion hreligion haven_labelled vctrs_vctr double
## hnation     hnation haven_labelled vctrs_vctr double
## heduc         heduc haven_labelled vctrs_vctr double
## hdiploma   hdiploma haven_labelled vctrs_vctr double
## hhandig     hhandig haven_labelled vctrs_vctr double
## hactiv7j   hactiv7j haven_labelled vctrs_vctr double
## hactiv12m hactiv12m haven_labelled vctrs_vctr double
## hbranch     hbranch haven_labelled vctrs_vctr double
## hsectins   hsectins haven_labelled vctrs_vctr double
## hcsp           hcsp haven_labelled vctrs_vctr double
## dali           dali                          numeric
## dnal           dnal                          numeric
## dtot           dtot                          numeric
## pcexp         pcexp                          numeric
## zzae           zzae                          numeric
## zref           zref                          numeric
## def_spa     def_spa                          numeric
## def_temp   def_temp                          numeric
##                                  Type_2021 Same_Type
## country                          character      TRUE
## year                               numeric      TRUE
## hhid                               numeric      TRUE
## grappe                             numeric      TRUE
## menage                             numeric      TRUE
## vague                              numeric      TRUE
## zae       haven_labelled vctrs_vctr double     FALSE
## region    haven_labelled vctrs_vctr double      TRUE
## milieu    haven_labelled vctrs_vctr double      TRUE
## hhweight                           numeric      TRUE
## hhsize                             numeric      TRUE
## eqadu1                             numeric      TRUE
## eqadu2                             numeric      TRUE
## hgender   haven_labelled vctrs_vctr double      TRUE
## hage                               numeric      TRUE
## hmstat    haven_labelled vctrs_vctr double      TRUE
## hreligion haven_labelled vctrs_vctr double      TRUE
## hnation   haven_labelled vctrs_vctr double      TRUE
## heduc     haven_labelled vctrs_vctr double      TRUE
## hdiploma  haven_labelled vctrs_vctr double      TRUE
## hhandig   haven_labelled vctrs_vctr double      TRUE
## hactiv7j  haven_labelled vctrs_vctr double      TRUE
## hactiv12m haven_labelled vctrs_vctr double      TRUE
## hbranch   haven_labelled vctrs_vctr double      TRUE
## hsectins  haven_labelled vctrs_vctr double      TRUE
## hcsp      haven_labelled vctrs_vctr double      TRUE
## dali                               numeric      TRUE
## dnal                               numeric      TRUE
## dtot                               numeric      TRUE
## pcexp                              numeric      TRUE
## zzae                               numeric      TRUE
## zref                               numeric      TRUE
## def_spa                            numeric      TRUE
## def_temp                           numeric      TRUE
\end{verbatim}

On remarque que ces variables communes sont bien de meme type pour les
deux bases et maintenant nous allons voir si les label pour les
variables catégorielles communes sont identiques dans les deux bases
sauf pour la variables zae zone agroécologique) qui dans la base 2018
est numeric et sans correspondances de labels pour chaque levels, tandis
que dans la base 2021 elle est bien labellisé, de ce fait regardons
d'abord si pour cette variable les valeurs prises dans les deux bases
sont les memes.

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Regardonc les modalités de la variable zae dans les deux bases }
\FunctionTok{unique}\NormalTok{(welfare\_2018}\SpecialCharTok{$}\NormalTok{zae)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1 5 3 2 4 6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unique}\NormalTok{(welfare\_2021}\SpecialCharTok{$}\NormalTok{zae)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## <labelled<double>[6]>: Zone agroecologique
## [1] 11  9  5  3  7  1
## 
## Labels:
##  value                          label
##      1                       Kédougou
##      3              Saint-Louis-Matam
##      5           Thies-Diourbel-Louga
##      7        Kaolack-Fatick-Kaffrine
##      9 Ziguinchor-Tamba-Kolda-Sédhiou
##     11                          Dakar
\end{verbatim}

On remarque meme que tandis qu'en 2018, cette variable prend les valeurs
1,5,3,2,4 et 6; en 2021, les valeurs prises sont plutot 1,3, 5,7,9 et
11. Et donc on ne saurait faire de correspondances. Pour le moment, nous
allons continuer le travail avec les autres variables communes.

\hypertarget{verification-de-la-correspondance-de-labels}{%
\subsubsection{Verification de la correspondance de
labels}\label{verification-de-la-correspondance-de-labels}}

On va afficher les level+labels de toutes les variables communes
catégorielles des deux bases. Puis on va identifier celles qui ont des
level+labels differentes pour les variables communes.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Initialisation d\textquotesingle{}une liste pour stocker les différences de labels}
\NormalTok{differences\_labels }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{()}

\CommentTok{\# Parcours de chaque variable commune}
\ControlFlowTok{for}\NormalTok{ (var }\ControlFlowTok{in}\NormalTok{ vars\_communes) \{}

  \CommentTok{\# Vérifions l\textquotesingle{}existence de la variable dans les deux bases}
  \ControlFlowTok{if}\NormalTok{ (var }\SpecialCharTok{\%in\%} \FunctionTok{colnames}\NormalTok{(welfare\_2018) }\SpecialCharTok{\&}\NormalTok{ var }\SpecialCharTok{\%in\%} \FunctionTok{colnames}\NormalTok{(welfare\_2021)) \{}
    
    \CommentTok{\# Récupérons les labels avec la fonction val\_labels() }
\NormalTok{    labels\_2018 }\OtherTok{\textless{}{-}}\NormalTok{ labelled}\SpecialCharTok{::}\FunctionTok{val\_labels}\NormalTok{(welfare\_2018[[var]])}
\NormalTok{    labels\_2021 }\OtherTok{\textless{}{-}}\NormalTok{ labelled}\SpecialCharTok{::}\FunctionTok{val\_labels}\NormalTok{(welfare\_2021[[var]])}
    
    \CommentTok{\# Vérifions s\textquotesingle{}il y a des différences entre }
    \CommentTok{\# les labels des deux années}
    \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{identical}\NormalTok{(labels\_2018, labels\_2021)) \{}
\NormalTok{      differences\_labels[[var]] }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}\StringTok{"2018"} \OtherTok{=}\NormalTok{ labels\_2018,}
                                        \StringTok{"2021"} \OtherTok{=}\NormalTok{ labels\_2021)}
\NormalTok{    \}}
\NormalTok{  \}}
\NormalTok{\}}

\CommentTok{\# Affichons les variables ayant des labels différents}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Variables ayant des labels différents entre 2018 et 2021 : "}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Variables ayant des labels différents entre 2018 et 2021 :
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(differences\_labels)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $zae
## $zae$`2018`
## NULL
## 
## $zae$`2021`
##                       Kédougou              Saint-Louis-Matam 
##                              1                              3 
##           Thies-Diourbel-Louga        Kaolack-Fatick-Kaffrine 
##                              5                              7 
## Ziguinchor-Tamba-Kolda-Sédhiou                          Dakar 
##                              9                             11 
## 
## 
## $hnation
## $hnation$`2018`
##                   Benin            Burkina Faso           Côte d'Ivoire 
##                       1                       2                       3 
##           Guinée Bissau                    Mali                   Niger 
##                       4                       5                       6 
##                 Sénégal                    Togo                 Nigéria 
##                       7                       8                       9 
##            Autre CEDEAO           Autre Afrique Autre pays hors Afrique 
##                      10                      11                      12 
## 
## $hnation$`2021`
##                   Bénin            Burkina Faso               Cape-vert 
##                       1                       2                       3 
##           Cote d'ivoire                  Gambie                   Ghana 
##                       4                       5                       6 
##                  Guinee           Guinée Bissau                 Liberia 
##                       7                       8                       9 
##                    Mali                   Niger                 Nigeria 
##                      10                      11                      12 
##                 Sénégal            Serra-Leonne                    Togo 
##                      13                      14                      15 
##           Autre Afrique Autre pays hors Afrique 
##                      17                      18 
## 
## 
## $hdiploma
## $hdiploma$`2018`
##           Aucun        CEP/CFEE       BEPC/BFEM             cap              bt 
##               0               1               2               3               4 
##             bac  DEUG, DUT, BTS         Licence        Maitrise Master/DEA/DESS 
##               5               6               7               8               9 
##    Doctorat/Phd 
##              10 
## 
## $hdiploma$`2021`
##           Aucun            cepe            bepc             cap              bt 
##               0               1               2               3               4 
##             bac  DEUG, DUT, BTS         Licence        Maitrise Master/DEA/DESS 
##               5               6               7               8               9 
##    Doctorat/Phd 
##              10 
## 
## 
## $hactiv7j
## $hactiv7j$`2018`
##              Occupe             Chomeur TF cherchant emploi    TF cherchant pas 
##                   1                   2                   3                   4 
##             Inactif      Moins de 5 ans 
##                   5                   6 
## 
## $hactiv7j$`2021`
##              Occupe TF cherchant emploi    TF cherchant pas             Chomeur 
##                   1                   2                   3                   4 
##             Inactif      Moins de 5 ans 
##                   5                   6 
## 
## 
## $hbranch
## $hbranch$`2018`
##      Agriculture    Elevage/peche    Indust. extr.    Autr. indust. 
##                1                2                3                4 
##              btp         Commerce Restaurant/Hotel     Trans./Comm. 
##                5                6                7                8 
##  Education/Sante  Services perso.    Aut. services 
##                9               10               11 
## 
## $hbranch$`2021`
##        Agriculture Elevage/syl./peche      Indust. extr.      Autr. indust. 
##                  1                  2                  3                  4 
##                btp           Commerce   Restaurant/Hotel       Trans./Comm. 
##                  5                  6                  7                  8 
##    Education/Sante    Services perso.      Aut. services 
##                  9                 10                 11 
## 
## 
## $hcsp
## $hcsp$`2018`
##                                             Cadre supérieur 
##                                                           1 
##                               Cadre moyen/agent de maîtrise 
##                                                           2 
##                                 Ouvrier ou employé qualifié 
##                                                           3 
##                             Ouvrier ou employé non qualifié 
##                                                           4 
##                                     Manœuvre, aide ménagère 
##                                                           5 
##                              Stagiaire ou Apprenti rénuméré 
##                                                           6 
##                          Stagiaire ou Apprenti non rénuméré 
##                                                           7 
## Travailleur familial contribuant à une entreprise familiale 
##                                                           8 
##                              Travailleur pour compte propre 
##                                                           9 
##                                                      Patron 
##                                                          10 
## 
## $hcsp$`2021`
##                                               Cadre supérieur 
##                                                             1 
##                                 Cadre moyen/agent de maîtrise 
##                                                             2 
##                                   Ouvrier ou employé qualifié 
##                                                             3 
##                               Ouvrier ou employé non qualifié 
##                                                             4 
##                                       Manœuvre, aide ménagère 
##                                                             5 
##                                Stagiaire ou Apprenti rénuméré 
##                                                             6 
##                            Stagiaire ou Apprenti non rénuméré 
##                                                             7 
## Travailleur Familial contribuant pour une entreprise familial 
##                                                             8 
##                                Travailleur pour compte propre 
##                                                             9 
##                                                        Patron 
##                                                            10
\end{verbatim}

On remarque une divergence de labels pour les variables hnation,
hdiploma, hactiv7j, hbranch et hcsp (sachant que la variable zae est
d'abord mise de coté car on ne saurait faire la correspondance).

\hypertarget{correction-pour-lharmonisation-des-labels-des-variables-communes}{%
\subsection{5- Correction pour l'harmonisation des labels des variables
communes}\label{correction-pour-lharmonisation-des-labels-des-variables-communes}}

Dans cette étape, nous corrigeons les labels des variables divergentes
pour les harmoniser entre 2018 et 2021.Nous allons procéder variable par
variable.

\hypertarget{variable-hnation}{%
\subsubsection{Variable hnation:}\label{variable-hnation}}

Nous allons ajuster les codes de 2021 pour qu'ils correspondent à ceux
de 2018. En effet, dans la base 2021, les autres pays de la CEDEAO ont
été détaillés individuellement, tandis que dans la base 2018, ces pays
étaient regroupés, donc c'est ce processus qui semble plus simple et
judicieux. Par la suite, on verifie que les correspondances avec les
effectifs sont bien maintenus.

En effet, Dans la base 2021, la variable hnation est définie avec 18
codes, où 1 = Bénin, 2 = Burkina Faso, 3 = Cape-vert, 4 = Cote d'ivoire,
5 = Gambie, 6 = Ghana, 7 = Guinee, 8 = Guinée Bissau, 9 = Liberia, 10 =
Mali, 11 = Niger, 12 = Nigeria, 13 = Sénégal, 14 = Serra-Leonne, 15 =
Togo, 17 = Autre Afrique et 18 = Autre pays hors Afrique.

En revanche, dans la base 2018, la variable hnation utilise 12 codes
dont 10 apparaissent dans les données, avec 1 = Benin, 2 = Burkina Faso,
3 = Côte d'Ivoire, 4 = Guinée Bissau, 5 = Mali, 6 = Niger, 7 = Sénégal,
8 = Togo, 9 = Nigéria, 10 = Autre CEDEAO, 11 = Autre Afrique et 12 =
Autre pays hors Afrique.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Création de copies des bases pour modification}
\NormalTok{base2021\_modifiee }\OtherTok{\textless{}{-}}\NormalTok{ welfare\_2021}
\NormalTok{base2018\_modifiee }\OtherTok{\textless{}{-}}\NormalTok{ welfare\_2018}

\CommentTok{\# 1. Visualisation des fréquences initiales }
\CommentTok{\#de la variable hnation dans la base 2021}

\CommentTok{\# Ici, nous utilisons la fonction to\_factor() du package}
\CommentTok{\# haven pour convertir les valeurs en facteurs }
\CommentTok{\# et observer les libellés.}

\NormalTok{freq\_avant }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\FunctionTok{to\_factor}\NormalTok{(welfare\_2021}\SpecialCharTok{$}\NormalTok{hnation))}
\FunctionTok{print}\NormalTok{(freq\_avant)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##                   Bénin            Burkina Faso               Cape-vert 
##                       0                       0                       0 
##           Cote d'ivoire                  Gambie                   Ghana 
##                       1                       2                       1 
##                  Guinee           Guinée Bissau                 Liberia 
##                      39                       8                       0 
##                    Mali                   Niger                 Nigeria 
##                      18                       2                       1 
##                 Sénégal            Serra-Leonne                    Togo 
##                    7038                       0                       1 
##           Autre Afrique Autre pays hors Afrique 
##                       7                       2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Correction des codes dans la base 2021 pour harmoniser avec 2018}
\NormalTok{base2021\_modifiee }\OtherTok{\textless{}{-}}\NormalTok{ base2021\_modifiee }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{hnation =} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{as.character}\NormalTok{(hnation))}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{dplyr}\SpecialCharTok{::}\FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{hnation =}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{case\_when}\NormalTok{(}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{1} \SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{,    }\CommentTok{\# Le level de Bénin est le meme}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{2} \SpecialCharTok{\textasciitilde{}} \DecValTok{2}\NormalTok{,    }\CommentTok{\# Le level de Burkina Faso est le meme}
      \CommentTok{\# Cape{-}vert entre dans "Autre CEDEAO"}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{3} \SpecialCharTok{\textasciitilde{}} \DecValTok{10}\NormalTok{,}
      \CommentTok{\# Le 4 de la Cote d\textquotesingle{}Ivoire est plutot 3 dans la base 2018}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{4} \SpecialCharTok{\textasciitilde{}} \DecValTok{3}\NormalTok{,   }
      \CommentTok{\# Gambie est mis dans "Autre CEDEAO"}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{5} \SpecialCharTok{\textasciitilde{}} \DecValTok{10}\NormalTok{,}
      \CommentTok{\# Ghana est intégré dans "Autre CEDEAO"}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{6} \SpecialCharTok{\textasciitilde{}} \DecValTok{10}\NormalTok{,  }
      \CommentTok{\# Guinee est intégré dans "Autre CEDEAO"}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{7} \SpecialCharTok{\textasciitilde{}} \DecValTok{10}\NormalTok{,}
      \CommentTok{\# Le 8 de la Guinee Bissau est plutot 4 dans la base 2018}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{8} \SpecialCharTok{\textasciitilde{}} \DecValTok{4}\NormalTok{,    }
      \CommentTok{\# Liberia est intégré dans "Autre CEDEAO"}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{9} \SpecialCharTok{\textasciitilde{}} \DecValTok{10}\NormalTok{,}
      \CommentTok{\# Le 10 de la Mali est plutot 5 dans la base 2018}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{10} \SpecialCharTok{\textasciitilde{}} \DecValTok{5}\NormalTok{,   }
      \CommentTok{\# Le 11 du Niger est plutot 6 dans la base 2018}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{11} \SpecialCharTok{\textasciitilde{}} \DecValTok{6}\NormalTok{,  }
      \CommentTok{\# Le 12 du Nigeria est plutot 9 dans la base 2018}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{12} \SpecialCharTok{\textasciitilde{}} \DecValTok{9}\NormalTok{,   }
      \CommentTok{\# Le 13 du Senegal est plutot 7 dans la base 2018}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{13} \SpecialCharTok{\textasciitilde{}} \DecValTok{7}\NormalTok{, }
      \CommentTok{\# Serra{-}Leonne est intégré dans "Autre CEDEAO"}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{14} \SpecialCharTok{\textasciitilde{}} \DecValTok{10}\NormalTok{, }
      \CommentTok{\# Le 15 du Togo est plutot 8 dans la base 2018}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{15} \SpecialCharTok{\textasciitilde{}} \DecValTok{8}\NormalTok{, }
      \CommentTok{\# La correspondance 17 du Autre Afrique }
      \CommentTok{\# est plutot 11 dans la base 2018}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{17} \SpecialCharTok{\textasciitilde{}} \DecValTok{11}\NormalTok{,  }
      \CommentTok{\# Le 18 du Autre pays hors Afrique }
      \CommentTok{\# est plutot 12 dans la base 2018}
\NormalTok{      hnation }\SpecialCharTok{==} \DecValTok{18} \SpecialCharTok{\textasciitilde{}} \DecValTok{12}\NormalTok{,  }
      \ConstantTok{TRUE} \SpecialCharTok{\textasciitilde{}} \ConstantTok{NA\_real\_}
\NormalTok{    )}
\NormalTok{  )}

\CommentTok{\# Attribution des labels pour la variable hnation dans la base 2021 }
\CommentTok{\#Ici, nous utilisons la fonction labelled() du package labelled }
\CommentTok{\# pour redéfinir les libellés en fonction des codes harmonisés.}
\NormalTok{base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hnation }\OtherTok{\textless{}{-}} \FunctionTok{labelled}\NormalTok{(}
\NormalTok{  base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hnation,}
  \FunctionTok{c}\NormalTok{(}
    \StringTok{"Benin"} \OtherTok{=} \DecValTok{1}\NormalTok{,}
    \StringTok{"Burkina Faso"} \OtherTok{=} \DecValTok{2}\NormalTok{,}
    \StringTok{"Côte d\textquotesingle{}Ivoire"} \OtherTok{=} \DecValTok{3}\NormalTok{,}
    \StringTok{"Guinée Bissau"} \OtherTok{=} \DecValTok{4}\NormalTok{,}
    \StringTok{"Mali"} \OtherTok{=} \DecValTok{5}\NormalTok{,}
    \StringTok{"Niger"} \OtherTok{=} \DecValTok{6}\NormalTok{,}
    \StringTok{"Sénégal"} \OtherTok{=} \DecValTok{7}\NormalTok{,}
    \StringTok{"Togo"} \OtherTok{=} \DecValTok{8}\NormalTok{,}
    \StringTok{"Nigéria"} \OtherTok{=} \DecValTok{9}\NormalTok{,}
    \StringTok{"Autre CEDEAO"} \OtherTok{=} \DecValTok{10}\NormalTok{,}
    \StringTok{"Autre Afrique"} \OtherTok{=} \DecValTok{11}\NormalTok{,}
    \StringTok{"Autre pays hors Afrique"} \OtherTok{=} \DecValTok{12}
\NormalTok{  )}
\NormalTok{)}

\CommentTok{\# 4. Vérification finale : affichage des fréquences après recodage }
\CommentTok{\#pour confirmer la correspondance avec la base 2018}

\NormalTok{freq\_apres }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\FunctionTok{to\_factor}\NormalTok{(base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hnation))}
\FunctionTok{print}\NormalTok{(freq\_apres)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##                   Benin            Burkina Faso           Côte d'Ivoire 
##                       0                       0                       1 
##           Guinée Bissau                    Mali                   Niger 
##                       8                      18                       2 
##                 Sénégal                    Togo                 Nigéria 
##                    7038                       1                       1 
##            Autre CEDEAO           Autre Afrique Autre pays hors Afrique 
##                      42                       7                       2
\end{verbatim}

Après vérification, on constate que les effectifs de chaque modalité ont
été conservés après harmonisation de labellisation.

\hypertarget{variable-hactiv7j}{%
\subsubsection{Variable hactiv7j}\label{variable-hactiv7j}}

Dans la base 2021, la variable hactiv7j présente une inversion dans la
codification par rapport à la base 2018. Concrètement, dans la base
2018, le code 2 correspond à TF cherchant emploi et le code 4 à Chômeur,
alors que dans la base 2021, ces codes sont inversés. Pour harmoniser
les deux bases, nous allons recoder la variable hactiv7j de 2021 afin
d'adapter sa structure à celle de 2018. Nous vérifierons ensuite que les
effectifs de chaque modalité sont correctement conservés après recodage.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualisation initiale des fréquences de hactiv7j de 2021 }

\NormalTok{freq\_avant }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\FunctionTok{to\_factor}\NormalTok{(welfare\_2021}\SpecialCharTok{$}\NormalTok{hactiv7j))}
\FunctionTok{print}\NormalTok{(freq\_avant)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##              Occupe TF cherchant emploi    TF cherchant pas             Chomeur 
##                5178                   5                  62                  34 
##             Inactif      Moins de 5 ans 
##                1841                   0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Correction: Recodage de hactiv7j dans la base 2021 }
\CommentTok{\# pour harmoniser la codification avec la base 2018.}

\CommentTok{\# Recodage numérique selon correspondance 2021 → 2018}
\CommentTok{\#   Code 1 reste 1 (Occupe)}
\CommentTok{\#   Code 2 devient 3 (TF cherchant emploi)}
\CommentTok{\#   Code 3 devient 4 (TF cherchant pas)}
\CommentTok{\#   Code 4 devient 2 (Chômeur)}
\CommentTok{\#   Codes 5 et 6 restent inchangés (Inactif et Moins de 5 ans)}

\NormalTok{base2021\_modifiee }\OtherTok{\textless{}{-}}\NormalTok{ base2021\_modifiee }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{hactiv7j =} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{      hactiv7j }\SpecialCharTok{==} \DecValTok{1} \SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{,}
\NormalTok{      hactiv7j }\SpecialCharTok{==} \DecValTok{2} \SpecialCharTok{\textasciitilde{}} \DecValTok{3}\NormalTok{,}
\NormalTok{      hactiv7j }\SpecialCharTok{==} \DecValTok{3} \SpecialCharTok{\textasciitilde{}} \DecValTok{4}\NormalTok{,}
\NormalTok{      hactiv7j }\SpecialCharTok{==} \DecValTok{4} \SpecialCharTok{\textasciitilde{}} \DecValTok{2}\NormalTok{,}
\NormalTok{      hactiv7j }\SpecialCharTok{==} \DecValTok{5} \SpecialCharTok{\textasciitilde{}} \DecValTok{5}\NormalTok{,}
\NormalTok{      hactiv7j }\SpecialCharTok{==} \DecValTok{6} \SpecialCharTok{\textasciitilde{}} \DecValTok{6}\NormalTok{,}
      \ConstantTok{TRUE} \SpecialCharTok{\textasciitilde{}} \ConstantTok{NA\_real\_}
\NormalTok{    )}
\NormalTok{  )}

\CommentTok{\# Attribution des labels pour hactiv7j dans la base 2021 modifiée,}
\CommentTok{\# en s\textquotesingle{}assurant que la correspondance avec la base 2018 est respectée.}

\NormalTok{base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hactiv7j }\OtherTok{\textless{}{-}} \FunctionTok{labelled}\NormalTok{(}
\NormalTok{  base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hactiv7j,}
  \FunctionTok{c}\NormalTok{(}
    \StringTok{"Occupe"} \OtherTok{=} \DecValTok{1}\NormalTok{,}
    \StringTok{"Chomeur"} \OtherTok{=} \DecValTok{2}\NormalTok{,}
    \StringTok{"TF cherchant emploi"} \OtherTok{=} \DecValTok{3}\NormalTok{,}
    \StringTok{"TF cherchant pas"} \OtherTok{=} \DecValTok{4}\NormalTok{,}
    \StringTok{"Inactif"} \OtherTok{=} \DecValTok{5}\NormalTok{,}
    \StringTok{"Moins de 5 ans"} \OtherTok{=} \DecValTok{6}
\NormalTok{  )}
\NormalTok{)}

\CommentTok{\# Vérification finale : affichage des fréquences après recodage }
\CommentTok{\# pour confirmer la conservation des effectifs}

\NormalTok{freq\_apres }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\FunctionTok{to\_factor}\NormalTok{(base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hactiv7j))}
\FunctionTok{print}\NormalTok{(freq\_apres)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##              Occupe             Chomeur TF cherchant emploi    TF cherchant pas 
##                5178                  34                   5                  62 
##             Inactif      Moins de 5 ans 
##                1841                   0
\end{verbatim}

\hypertarget{variable-hdiploma}{%
\subsubsection{Variable hdiploma}\label{variable-hdiploma}}

Dans la base de 2021, les diplômes sont nommés différemment de ceux de
2018. Nous allons donc uniformiser les noms en harmonisant CEP/CFEE et
BEPC/BFEM qui étaient écrits cepe et bepc respectivement dans la base
2021.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualisation des fréquences avant modification}
\NormalTok{freq\_avant }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\FunctionTok{to\_factor}\NormalTok{(welfare\_2021}\SpecialCharTok{$}\NormalTok{hdiploma))}
\FunctionTok{print}\NormalTok{(freq\_avant)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##           Aucun            cepe            bepc             cap              bt 
##            5772             583             317              39               7 
##             bac  DEUG, DUT, BTS         Licence        Maitrise Master/DEA/DESS 
##             150              46             101              55              32 
##    Doctorat/Phd 
##              18
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# CORRECTION DES LABELS }

\CommentTok{\# 1. Extraction des labels actuels de la variable hdiploma}
\NormalTok{labels\_avant }\OtherTok{\textless{}{-}} \FunctionTok{attr}\NormalTok{(base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hdiploma, }\StringTok{"labels"}\NormalTok{)}

\CommentTok{\# 2. Identification des codes correspondant aux diplômes à renommer}
\NormalTok{code\_cepe }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(labels\_avant }\SpecialCharTok{==} \DecValTok{1}\NormalTok{)  }
\NormalTok{code\_bepc }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(labels\_avant }\SpecialCharTok{==} \DecValTok{2}\NormalTok{)  }

\CommentTok{\# 3. Modification des labels sans changer leur level car correct}
\FunctionTok{names}\NormalTok{(labels\_avant)[code\_cepe] }\OtherTok{\textless{}{-}} \StringTok{"CEP/CFEE"} 
\FunctionTok{names}\NormalTok{(labels\_avant)[code\_bepc] }\OtherTok{\textless{}{-}} \StringTok{"BEPC/BFEM"}

\CommentTok{\# 4. Réassignation des labels mis à jour}
\FunctionTok{attr}\NormalTok{(base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hdiploma, }\StringTok{"labels"}\NormalTok{) }\OtherTok{\textless{}{-}}\NormalTok{ labels\_avant}

\CommentTok{\# Vérification après modification}
\NormalTok{freq\_apres }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\FunctionTok{to\_factor}\NormalTok{(base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hdiploma))}
\FunctionTok{print}\NormalTok{(freq\_apres)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##           Aucun        CEP/CFEE       BEPC/BFEM             cap              bt 
##            5772             583             317              39               7 
##             bac  DEUG, DUT, BTS         Licence        Maitrise Master/DEA/DESS 
##             150              46             101              55              32 
##    Doctorat/Phd 
##              18
\end{verbatim}

Après harmonisation, nous avons bien aligné les labels CEP/CFEE et
BEPC/BFEM avec ceux de 2018, tout en conservant les effectifs de chaque
modalité.

\hypertarget{hbranch}{%
\subsubsection{hbranch}\label{hbranch}}

Dans la base de 2021, le niveau 2 de hbranch inclut la sylviculture en
plus de l'élevage et de la pêche (c'est Elevage/syl./peche). Pour
assurer l'uniformité avec 2018, nous allons mettre à jour le libellé
correspondant.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualisation des fréquences avant modification}
\NormalTok{freq\_avant }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\FunctionTok{to\_factor}\NormalTok{(welfare\_2018}\SpecialCharTok{$}\NormalTok{hbranch))}
\FunctionTok{print}\NormalTok{(freq\_avant)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##      Agriculture    Elevage/peche    Indust. extr.    Autr. indust. 
##             1366              374               58              497 
##              btp         Commerce Restaurant/Hotel     Trans./Comm. 
##              313             1094               63              251 
##  Education/Sante  Services perso.    Aut. services 
##              379              761              278
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# CORRECTION DES LABELS (sans changer le type )}

\CommentTok{\# Extraction des labels actuels de la variable hbranch}
\NormalTok{labels\_avant }\OtherTok{\textless{}{-}} \FunctionTok{attr}\NormalTok{(base2018\_modifiee}\SpecialCharTok{$}\NormalTok{hbranch, }\StringTok{"labels"}\NormalTok{)}

\CommentTok{\# Identification du code correspondant au niveau 2}
\NormalTok{code\_level2 }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(labels\_avant }\SpecialCharTok{==} \DecValTok{2}\NormalTok{)  }

\CommentTok{\# Modification du libellé en ajoutant la sylviculture}
\FunctionTok{names}\NormalTok{(labels\_avant)[code\_level2] }\OtherTok{\textless{}{-}} \StringTok{"Elevage/syl./peche"}

\CommentTok{\# Réassignation des labels mis à jour}
\FunctionTok{attr}\NormalTok{(base2018\_modifiee}\SpecialCharTok{$}\NormalTok{hbranch, }\StringTok{"labels"}\NormalTok{) }\OtherTok{\textless{}{-}}\NormalTok{ labels\_avant}

\CommentTok{\# Vérification après modification}
\NormalTok{freq\_apres }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\FunctionTok{to\_factor}\NormalTok{(base2018\_modifiee}\SpecialCharTok{$}\NormalTok{hbranch))}
\FunctionTok{print}\NormalTok{(freq\_apres)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##        Agriculture Elevage/syl./peche      Indust. extr.      Autr. indust. 
##               1366                374                 58                497 
##                btp           Commerce   Restaurant/Hotel       Trans./Comm. 
##                313               1094                 63                251 
##    Education/Sante    Services perso.      Aut. services 
##                379                761                278
\end{verbatim}

Après cette mise à jour, nous avons bien intégré la sylviculture dans la
modalité correspondante de 2018. Les effectifs des différentes
catégories restent bien inchangés.

\hypertarget{hcsp}{%
\subsubsection{hcsp}\label{hcsp}}

Dans la base de 2021, l'intitulé du label correspondant à la valeur 8
est ``Travailleur contribuant pour une entreprise familiale''.
Cependant, dans la base de 2018, la version correcte est ``Travailleur
contribuant à une entreprise familiale''. Et comme en francais, la forme
la plus correcte est ``Travailleur contribuant à une entreprise
familiale'', nous modifions le libellé de 2021 pour qu'il corresponde à
la version de 2018.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualisation des fréquences avant correction}
\NormalTok{freq\_avant }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\FunctionTok{to\_factor}\NormalTok{(welfare\_2021}\SpecialCharTok{$}\NormalTok{hcsp))}
\FunctionTok{print}\NormalTok{(freq\_avant)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##                                               Cadre supérieur 
##                                                            57 
##                                 Cadre moyen/agent de maîtrise 
##                                                           280 
##                                   Ouvrier ou employé qualifié 
##                                                           450 
##                               Ouvrier ou employé non qualifié 
##                                                           332 
##                                       Manœuvre, aide ménagère 
##                                                           151 
##                                Stagiaire ou Apprenti rénuméré 
##                                                            34 
##                            Stagiaire ou Apprenti non rénuméré 
##                                                             3 
## Travailleur Familial contribuant pour une entreprise familial 
##                                                            66 
##                                Travailleur pour compte propre 
##                                                          4302 
##                                                        Patron 
##                                                           119
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# CORRECTION DES LABELS }

\CommentTok{\# Extraction des labels actuels}
\NormalTok{labels\_avant }\OtherTok{\textless{}{-}} \FunctionTok{attr}\NormalTok{(base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hcsp, }\StringTok{"labels"}\NormalTok{)}

\CommentTok{\# Identification du code à modifier}
\NormalTok{code\_level8 }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(labels\_avant }\SpecialCharTok{==} \DecValTok{8}\NormalTok{)  }

\CommentTok{\# Modification du libellé pour la valeur 8}
\FunctionTok{names}\NormalTok{(labels\_avant)[code\_level8] }\OtherTok{\textless{}{-}} 
  \StringTok{"Travailleur familial contribuant à une entreprise familiale"}

\CommentTok{\# Réassignation des labels corrigés}
\FunctionTok{attr}\NormalTok{(base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hcsp, }\StringTok{"labels"}\NormalTok{) }\OtherTok{\textless{}{-}}\NormalTok{ labels\_avant}

\CommentTok{\# Vérification après modification}
\NormalTok{freq\_apres }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(}\FunctionTok{to\_factor}\NormalTok{(base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hcsp))}
\FunctionTok{print}\NormalTok{(freq\_apres)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##                                             Cadre supérieur 
##                                                          57 
##                               Cadre moyen/agent de maîtrise 
##                                                         280 
##                                 Ouvrier ou employé qualifié 
##                                                         450 
##                             Ouvrier ou employé non qualifié 
##                                                         332 
##                                     Manœuvre, aide ménagère 
##                                                         151 
##                              Stagiaire ou Apprenti rénuméré 
##                                                          34 
##                          Stagiaire ou Apprenti non rénuméré 
##                                                           3 
## Travailleur familial contribuant à une entreprise familiale 
##                                                          66 
##                              Travailleur pour compte propre 
##                                                        4302 
##                                                      Patron 
##                                                         119
\end{verbatim}

L'harmonisation a bien été faite tout en conservant les effectifs de
chaque modalité.

\hypertarget{vuxe9rification-de-la-correspondance-des-labels-entre-les-variables}{%
\subsection{6- Vérification de la correspondance des labels entre les
variables}\label{vuxe9rification-de-la-correspondance-des-labels-entre-les-variables}}

Nous allons maintenant comparer les labels des variables harmonisées
entre les bases de 2018 et 2021 afin de nous assurer qu'ils sont bien
identiques après les corrections effectuées.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Charger le package nécessaire}
\FunctionTok{library}\NormalTok{(labelled)}

\CommentTok{\# Fonction pour comparer les labels}
\NormalTok{compare\_labels }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(var1, var2, name) \{}
  \CommentTok{\# Labels de la variable dans la base 2018}
\NormalTok{  labels1 }\OtherTok{\textless{}{-}} \FunctionTok{val\_labels}\NormalTok{(var1) }
  \CommentTok{\# Labels de la variable dans la base 2021}
\NormalTok{  labels2 }\OtherTok{\textless{}{-}} \FunctionTok{val\_labels}\NormalTok{(var2)  }
  \CommentTok{\# Vérifie si les labels sont identiques}
\NormalTok{  identical\_labels }\OtherTok{\textless{}{-}} \FunctionTok{identical}\NormalTok{(labels1, labels2)  }
  
  \ControlFlowTok{if}\NormalTok{ (identical\_labels) \{}
    \FunctionTok{cat}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"Les labels de "}\NormalTok{, name,}
               \StringTok{" sont identiques dans les deux bases.}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{))}
\NormalTok{  \} }\ControlFlowTok{else}\NormalTok{ \{}
    \FunctionTok{cat}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"Les labels de "}\NormalTok{, name, }\StringTok{" sont différents.}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{))}
    \CommentTok{\# Labels présents dans 2018 mais pas en 2021}
    \FunctionTok{print}\NormalTok{(}\FunctionTok{setdiff}\NormalTok{(}\FunctionTok{names}\NormalTok{(labels1), }\FunctionTok{names}\NormalTok{(labels2)))}
    \CommentTok{\# Labels présents en 2021 mais pas en 2018}
    \FunctionTok{print}\NormalTok{(}\FunctionTok{setdiff}\NormalTok{(}\FunctionTok{names}\NormalTok{(labels2), }\FunctionTok{names}\NormalTok{(labels1)))  }
\NormalTok{  \}}
\NormalTok{\}}

\CommentTok{\# Comparer les labels des variables communes}
\FunctionTok{compare\_labels}\NormalTok{(base2018\_modifiee}\SpecialCharTok{$}\NormalTok{hcsp, }
\NormalTok{               base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hcsp, }\StringTok{"hcsp"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Les labels de hcsp sont identiques dans les deux bases.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{compare\_labels}\NormalTok{(base2018\_modifiee}\SpecialCharTok{$}\NormalTok{hbranch, }
\NormalTok{               base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hbranch, }\StringTok{"hbranch"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Les labels de hbranch sont identiques dans les deux bases.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{compare\_labels}\NormalTok{(base2018\_modifiee}\SpecialCharTok{$}\NormalTok{hdiploma, }
\NormalTok{               base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hdiploma, }\StringTok{"hdiploma"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Les labels de hdiploma sont identiques dans les deux bases.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{compare\_labels}\NormalTok{(base2018\_modifiee}\SpecialCharTok{$}\NormalTok{hactiv7j, }
\NormalTok{               base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hactiv7j, }\StringTok{"hactiv7j"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Les labels de hactiv7j sont identiques dans les deux bases.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{compare\_labels}\NormalTok{(base2018\_modifiee}\SpecialCharTok{$}\NormalTok{hnation, }
\NormalTok{               base2021\_modifiee}\SpecialCharTok{$}\NormalTok{hnation, }\StringTok{"hnation"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Les labels de hnation sont identiques dans les deux bases.
\end{verbatim}

Après exécution de cette vérification, nous constatons que les labels
sont bien harmonisés entre les deux bases. Nous pouvons donc passer à
l'étape suivante.

\hypertarget{renommage-des-variables-non-communes-aux-deux-bases}{%
\subsection{7- Renommage des variables non communes aux deux
bases}\label{renommage-des-variables-non-communes-aux-deux-bases}}

Afin de conserver une traçabilité des données spécifiques à chaque
année, nous allons ajouter le suffixe correspondant à l'année (\_2018 ou
\_2021) aux variables qui ne sont présentes que dans une seule des deux
bases.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 1. Identifions les variables spécifiques à chaque base}

\NormalTok{common\_vars }\OtherTok{\textless{}{-}} \FunctionTok{intersect}\NormalTok{(}\FunctionTok{names}\NormalTok{(base2018\_modifiee), }
                         \FunctionTok{names}\NormalTok{(base2021\_modifiee))}
\NormalTok{unique\_2018  }\OtherTok{\textless{}{-}} \FunctionTok{setdiff}\NormalTok{(}\FunctionTok{names}\NormalTok{(base2018\_modifiee), common\_vars)}
\NormalTok{unique\_2021  }\OtherTok{\textless{}{-}} \FunctionTok{setdiff}\NormalTok{(}\FunctionTok{names}\NormalTok{(base2021\_modifiee), common\_vars)}

\CommentTok{\# Affichage des variables spécifiques à chaque base}
\FunctionTok{print}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{ les variables uniquement présentes en 2018"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "\n les variables uniquement présentes en 2018"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(unique\_2018)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "halfab"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{ les variables uniquement présentes en 2021"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "\n les variables uniquement présentes en 2021"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(unique\_2021)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "month"                "hethnie"              "halfa"               
##  [4] "halfa2"               "def_temp_prix2021m11" "def_temp_cpi"        
##  [7] "def_temp_adj"         "zali0"                "dtet"                
## [10] "monthly_cpi"          "cpi2017"              "icp2017"             
## [13] "dollars"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 2. Renommage des variables spécifiques à chaque année}
\NormalTok{base2018\_modifiee }\OtherTok{\textless{}{-}}\NormalTok{ base2018\_modifiee }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{rename\_with}\NormalTok{(}\SpecialCharTok{\textasciitilde{}} \FunctionTok{paste0}\NormalTok{(.,}\StringTok{"\_2018"}\NormalTok{), }\FunctionTok{all\_of}\NormalTok{(unique\_2018))}

\NormalTok{base2021\_modifiee }\OtherTok{\textless{}{-}}\NormalTok{ base2021\_modifiee }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{rename\_with}\NormalTok{(}\SpecialCharTok{\textasciitilde{}} \FunctionTok{paste0}\NormalTok{(.,}\StringTok{"\_2021"}\NormalTok{), }\FunctionTok{all\_of}\NormalTok{(unique\_2021))}

\CommentTok{\# 3. Vérification du renommage}
\NormalTok{unique\_2018\_corr  }\OtherTok{\textless{}{-}} \FunctionTok{setdiff}\NormalTok{(}\FunctionTok{names}\NormalTok{(base2018\_modifiee), common\_vars)}
\NormalTok{unique\_2021\_corr  }\OtherTok{\textless{}{-}} \FunctionTok{setdiff}\NormalTok{(}\FunctionTok{names}\NormalTok{(base2021\_modifiee), common\_vars)}
\FunctionTok{print}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{ Vérication de la correction en 2018"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "\n Vérication de la correction en 2018"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(unique\_2018\_corr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "halfab_2018"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{ Vérication de la correction en 2021"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "\n Vérication de la correction en 2021"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(unique\_2021\_corr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "month_2021"                "hethnie_2021"             
##  [3] "halfa_2021"                "halfa2_2021"              
##  [5] "def_temp_prix2021m11_2021" "def_temp_cpi_2021"        
##  [7] "def_temp_adj_2021"         "zali0_2021"               
##  [9] "dtet_2021"                 "monthly_cpi_2021"         
## [11] "cpi2017_2021"              "icp2017_2021"             
## [13] "dollars_2021"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 4. Renommer aussi zae car la correspondance n\textquotesingle{}a pas été faite }
\CommentTok{\# Et donc pour cette variables, }
\CommentTok{\# nous distinguons zae pour l\textquotesingle{}année 2018 et pour 2021}
\NormalTok{base2018\_modifiee }\OtherTok{\textless{}{-}}\NormalTok{ base2018\_modifiee }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rename}\NormalTok{(}\AttributeTok{zae\_2018 =}\NormalTok{ zae)}

\NormalTok{base2021\_modifiee }\OtherTok{\textless{}{-}}\NormalTok{ base2021\_modifiee }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rename}\NormalTok{(}\AttributeTok{zae\_2021 =}\NormalTok{ zae)}
\end{Highlighting}
\end{Shaded}

\hypertarget{fusion-des-deux-bases}{%
\subsection{8- Fusion des deux bases}\label{fusion-des-deux-bases}}

Nous allons maintenant fusionner les bases de 2018 et 2021 en faisant un
append. Il y avait 34 variables communes (mais on n'a pas pu faire la
correspondance donc on la distinguera our l'année 2018 et pour 2021 et
donc ici ca fait deja 35variables) et 1 variable uniquement présentes
dans la base 2018 et 13 uniquement présentes en 2021, et donc dans la
base finale, il doit avoir 35+1+13= 49 variables. Et par ailleurs 7120
(en 2018) + 7156 (en 2021) observations= 14276 observations

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Append les deux bases}
\NormalTok{base\_finale }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(base2018\_modifiee, base2021\_modifiee)}

\CommentTok{\# Vérifier la structure finale}
\FunctionTok{print}\NormalTok{(}\FunctionTok{dim}\NormalTok{(base\_finale))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 14276    49
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Enregistrement}
\FunctionTok{write\_dta}\NormalTok{(base\_finale,}\StringTok{"../Sortie/base\_finale.dta"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Les statistiques prevues pour la base finale sont verifiées donc c'est
ok.

\end{document}
