---
title: "Projet R"
author: "Illy"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
library(gtsummary)
library(haven)
#install.packages("labelled")
library(labelled)
data <- read_dta("C:/Users/ANSD/Documents/GitHub/Projet-statistique-sous-R/TP 4/Statistiques_descriptives_ILLY_Jacques/ehcvm_menage_SEN2021.dta")
base<-read.csv("C:/Users/ANSD/Documents/GitHub/Projet-statistique-sous-R/TP 4/statistiques_descriptives_ILLY_Jacques/ehcvm_welfare_sen2021.csv")

```


```{r pressure, echo=FALSE}
names(data) #pour voir les nom des colonnes

data %>%  select(logem, toit,sol) %>%  tbl_summary()

```



```{r Basic codes}
###les tableaux doivent etre explicites. Toujours labelliser
data %>% to_factor()%>%select(logem, toit,sol) %>%tbl_summary()
```

```{r  modif du titre des tableaux}
###lDescription
data %>%
  to_factor() %>% # Convertir les variables catégorielles en facteurs
  select(logem, toit, sol) %>%
  tbl_summary(
    label = list(
      logem ~ "Type de logement du chef de ménage",
      toit ~ "Type de toit",
      sol ~ "Type de sol"
    )
  )%>% modify_header(label ~ "CARAK") ####MODIFIER LE TITRE DU TAB
```   



```{r  kaizen}
###lDescription
data %>%
  to_factor() %>% # Convertir les variables catégorielles en facteurs
  select(logem, toit, sol, superf,grosrum) %>%
  tbl_summary(
    label = list(
      logem ~ "Type de logement du chef de ménage",
      toit ~ "Type de toit",
      sol ~ "Type de sol",
      superf~ "superficie",
      grosrum~"Nombre de gros ruminants"
    ), 
    statistic = list(grosrum~ "{mean}({sd})", superf~ "{mean}({sd})")
  )
```
   



```{r  kaizen deux}
###lDescription
data %>%
  to_factor() %>% # Convertir les variables catégorielles en facteurs
  select(superf,grosrum) %>%
  tbl_summary(
    statistic = list(grosrum~ "{mean}({sd})", superf~ "{mean}({sd})")
  )
```  


```{r  kaizen trois}
###lDescription
data %>%
  to_factor() %>% # Convertir les variables catégorielles en facteurs
  select(superf,grosrum) %>%
  tbl_summary(
    statistic = list(grosrum~ "{mean}({sd})", superf~ "{mean}({sd})"),digits = everything()~c(0,0)) ###everything on veut arrondir pour toutes les variables sinon on aurait pu spécifier avec une liste de var// On a arrondi à 0 chiffres après la virgule
  
``` 


```{r  kaizen missings}
###lDescription
##missing = always pert de toujours afficher les missings
data %>%
  to_factor() %>% # Convertir les variables catégorielles en facteurs
  select(superf,grosrum) %>%
  tbl_summary(
    statistic = list(grosrum~ "{mean}({sd})", superf~ "{mean}({sd})"),digits = everything()~c(0,0), 
    missing = "always",
    missing_text= "Missing",)
```


```{r Basic codes}
###les tableaux doivent etre explicites. Toujours labelliser
base %>%select(hgender, hage,hmstat, heduc, hdiploma) %>%  to_factor()  %>%tbl_summary()
```

```{R}

```

