---
title: "Statistiques descriptives"
author: ""
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Liste des packages à installer et charger


```{r}

# Vérifier et installer chaque package si nécessaire

if (!require(readr)) install.packages("readr")
if (!require(utils)) install.packages("utils")
if (!require(dplyr)) install.packages("dplyr")

# Charger les packages
library(readr)
library(utils)
library(dplyr)
# Chargement des bibliothèques
library(tidyverse)
library(gtsummary)
library(survey)


```

# IMPORTATION DES DONNEES DES BASES

```{r}
#  Ménage

men <- utils::read.csv("../Données/ehcvm_individu_sen2021.csv")  

# Individu

ind <- utils::read.csv("../Données/ehcvm_individu_sen2021.csv")  

```

# STRUCURE DES BASES DE DONNEES

```{r}
# Base ménage

utils::str(men)


```
```{r}
# Base individu

utils::str(ind)

```


# Fusion



```{r}
# Fusion des bases individu et ménage en utilisant inner_join()

men_ind <- dplyr::inner_join(ind, men, by = "hhid")

# Afficher la base fusionnée
head(men_ind)

variable.names(men_ind)

# Nombre de valeurs manquantes pour chaque variable
colSums(is.na(men_ind))


```


```{r}
utils::str(men_ind)
```



## Statistiques descriptives


```{r}
# Sélection des variables pertinentes
men_ind_selected <- men_ind %>%
  select(
    Poids_Menage = hhweight.x,   
    Sexe = sexe.x,               
    Age = age.x,                 
    Statut_Matrimonial = mstat.x, 
    Religion = religion.x,       
    Ethnie = ethnie.x,           
    Niveau_Education = educ_hi.x, 
    Activite_7J = activ7j.x,     
    Scolarisation = scol.x,      
    Acces_Internet = internet.x, 
    Telephone_Portable = telpor.x, 
    Couverture_Maladie = couvmal.x 
  )

```



```{r}


men_ind_selected %>%
  tbl_cross(
    row = Niveau_Education,
    col = Acces_Internet,
    percent = "row",
    label = list(
      Niveau_Education = "Niveau d'éducation",
      Acces_Internet = "Accès à l'internet"
    )
  ) %>%
  add_p() %>%
  modify_header(
    label = "**Variables**", # En-tête pour les étiquettes
    stat_0 = "**Pourcentage**", # En-tête pour les statistiques
    p.value = "**p-valeur**" # En-tête pour les p-values
  ) %>% 
  bold_labels()

```


```{r}


# Sélection des variables d'intérêt et conversion en facteur si nécessaire
men_ind_selected <- men_ind %>%
  select(
    Poids = hhweight.x,      
    Sexe = sexe.x,           
    Niveau_Education = educ_hi.x, 
    Acces_Internet = internet.x, 
    Couverture_Maladie = couvmal.x 
  ) %>%
  mutate(across(c(Sexe, Niveau_Education, Acces_Internet, Couverture_Maladie), as.factor))

# Définition du design pondéré
men_ind_svy <- svydesign(ids = ~1, weights = ~Poids, data = men_ind_selected)

# Tableau des statistiques descriptives pondérées
tbl_svysummary(men_ind_svy) %>%
  bold_labels()

```

```{r}

survey::svydesign(~1, data = as.data.frame(men_ind_selected), weights = ~Poids) |>
  
tbl_svysummary(by = Sexe, percent = "column", include = c(Niveau_Education , Acces_Internet ))|>
  modify_spanning_header(all_stat_cols() ~ "**Sexe**")
```

