---
title: "Test de management et d’analyse des données avec R"
author: "Djerakei MISTALENGAR"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
  header-includes:
   - \usepackage{float}
  word_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, results="asis")
```

## Installation et chargement des packages

```{r  message=FALSE,warning = FALSE}

# Vérifier et installer les packages nécessaires

packages <- c("haven", "utils", "dplyr", "tidyverse", "gtsummary", "survey", "knitr")

for (pkg in packages) {
  if (!require(pkg, character.only = TRUE)) install.packages(pkg, dependencies = TRUE)
  library(pkg, character.only = TRUE)
}

```


```{r}
# Supprimer toutes les variables de l'environnement
rm(list = ls())
```

## Chargement des données

```{r}
# Chargement des fichiers

mbl <- haven::read_dta("../Données/food_comp_mother_baseline.dta")

mel <- haven::read_dta("../Données/food_comp_mother_endline.dta")

cbl <- haven::read_dta("../Données/food_comp_child_baseline.dta) ")

cel <- haven::read_dta("../Données/food_comp_child_endline.dta")

men <- haven::read_dta("../Données/base_menage.dta")


```
