---
title: "Untitled"
author: "Awa D"
date: "11/02/2025"
output: html_document
---

```{r}
# Installation nécessaires
packages <- c("haven", "gtsummary", "labelled")
install_if_missing <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg)
}
invisible(lapply(packages, install_if_missing))

# Charger les packages
library(haven)      # Pour importer les fichiers .dta (Stata)
library(gtsummary)  
library(labelled)
```

```{r importation de la base}
# Importer le fichier Stata (.dta)
ehcvm21_sen <- read_dta("./Data/ehcvm_menage_SEN2021.dta")
ehcvm21_sen_welfare <- read_dta("./Data/ehcvm_welfare_SEN2021.dta")
#names ou colnames pour afficher les noms des colonnes
names(ehcvm21_sen)
names(ehcvm21_sen_welfare)

```


```{r select variables}
names(ehcvm21_sen)
ehcvm21_sen %>%  select(logem, toit,sol) %>%  tbl_summary()
```

```{r Basic codes}
###les tableaux doivent etre explicites. Toujours labelliser
ehcvm21_sen %>% to_factor()%>%select(logem, toit,sol) %>%tbl_summary()
```

```{r  modif du titre des tableaux}
###lDescription
ehcvm21_sen %>%
  to_factor() %>% # Convertir les variables catégorielles en facteurs
  select(logem, toit, sol) %>%
  tbl_summary(
    label = list(
      logem ~ "Type de logement du chef de ménage",
      toit ~ "Type de toit",
      sol ~ "Type de sol"
    )
  )%>% modify_header(label ~ "CARAK") ####MODIFIER LE TITRE DU TAB
   
```


```{r  kaizen}
###lDescription
ehcvm21_sen %>%
  to_factor() %>% # Convertir les variables catégorielles en facteurs
  select(logem, toit, sol, superf,grosrum) %>%
  tbl_summary(
    label = list(
      logem ~ "Type de logement du chef de ménage",
      toit ~ "Type de toit",
      sol ~ "Type de sol",
      superf~ "superficie",
      grosrum~"Nombre de gros ruminants"
    ), 
    statistic = list(grosrum~ "{mean}({sd})", superf~ "{mean}({sd})")
  )
   
```


```{r  kaizen deux}
###lDescription
ehcvm21_sen %>%
  to_factor() %>% # Convertir les variables catégorielles en facteurs
  select(superf,grosrum) %>%
  tbl_summary(
    statistic = list(grosrum~ "{mean}({sd})", superf~ "{mean}({sd})")
  )
   
```

```{r  kaizen trois}
###lDescription
ehcvm21_sen %>%
  to_factor() %>% # Convertir les variables catégorielles en facteurs
  select(superf,grosrum) %>%
  tbl_summary(
    statistic = list(grosrum~ "{mean}({sd})", superf~ "{mean}({sd})"),digits = everything()~c(0,0) ###everything on veut arrondir pour toutes les variables sinon on aurait pu spécifier avec une liste de var// On a arrondi à 0 chiffres après la virgule
  )
   
```

```{r  kaizen missings}
###lDescription
##missing = always pert de toujours afficher les missings
ehcvm21_sen %>%
  to_factor() %>% # Convertir les variables catégorielles en facteurs
  select(superf,grosrum) %>%
  tbl_summary(
    statistic = list(grosrum~ "{mean}({sd})", superf~ "{mean}({sd})"),digits = everything()~c(0,0), 
    missing = "always",
    missing_text= "Missing",
  )
   
```



```{r  kaizen new dataset}

ehcvm21_sen_welfare %>%
  to_factor() %>% # Convertir les variables catégorielles en facteurs
  select(hage,hmstat,heduc,hdiploma ) %>%
  tbl_summary(
    #statistic = list( hage~ "{mean}({sd})"),digits = everything()~c(1),
    missing = "always",
    missing_text= "Missing"
  )
   
```
