---
title: "Statistiques_descriptives"
author: "Lawa Foumsou Prosper"
date: "`r Sys.Date()`"
output: html_document
---

```{r, , warning=FALSE, message=FALSE}
library("haven")
library("dplyr")
library("gtsummary")
library("labelled")
```

```{r, warning=FALSE}
base_men <- haven::read_dta("../données/ehcvm_menage_mli2021.dta", encoding = "latin1")
library(haven)
#base_men %>% colnames()
```

```{r}
base_men %>% select("logem","toit","sol") %>% tbl_summary()
```

```{r}
# Prendre en compte les babels
base_men %>% labelled::to_factor() %>% select("logem","toit","sol") %>% tbl_summary()
```

```{r}
# Labeliser les variables
base_men %>% labelled::to_factor() %>% select("logem","toit","sol") %>% tbl_summary(label= list(logem ~ "Occupation logement",toit ~ "Type de toit",sol ~ "Type de sol"))
```

```{r}
# Changer l'en tête characteristic
base_men %>% labelled::to_factor() %>% select("logem","toit","sol") %>% tbl_summary(label= list(logem ~ "Occupation logement",toit ~ "Type de toit",sol ~ "Type de sol")) %>% modify_header(label="Caractéristiques du logement")
```

```{r}
base_men %>% labelled::to_factor() %>% select("logem","toit","sol","superf","grosrum","petitrum") %>% tbl_summary(label= list(logem ~ "Occupation logement",toit ~ "Type de toit",sol ~ "Type de sol"),statistic = list(superf ~ "{mean} ({sd})",
                   grosrum ~ "{mean} ({sd})",
                   petitrum ~ "{mean} ({sd})")) %>% modify_header(label="Caractéristiques du logement")  %>% add_n() 
```

```{r}
base_men %>% labelled::to_factor() %>% select("logem","toit","sol","superf","grosrum","petitrum") %>% tbl_summary(label= list(logem ~ "Occupation logement",toit ~ "Type de toit",sol ~ "Type de sol"),statistic = list(superf ~ "{mean} ({sd})",
                   grosrum ~ "{mean} ({sd})",
                   petitrum ~ "{mean} ({sd})"),missing = "always",
                   missing_text = "manquant") %>% modify_header(label="Caractéristiques du logement")  %>% add_n() 
```

```{r}
base_men %>% labelled::to_factor() %>% select("logem","toit","sol","superf","grosrum","petitrum") %>% tbl_summary(label= list(logem ~ "Occupation logement",toit ~ "Type de toit",sol ~ "Type de sol"),statistic = list(superf ~ "{mean} ({sd})",
                   grosrum ~ "{mean} ({sd})",
                   petitrum ~ "{mean} ({sd})"),
                   digits = everything() ~ c(0,0,0),
                   missing = "always",
                   missing_text = "manquant") %>% modify_header(label="Caractéristiques du logement")  %>% add_n() 
```

```{r}
base_welfare <- haven::read_dta("../données/ehcvm_welfare_mli2021.dta")
#base_men %>% colnames()
```

```{r}
base_welfare %>% labelled::to_factor() %>% select("hgender","hage","hmstat","heduc","hdiploma") %>% tbl_summary(label= list(hgender ~ "Sexe du CM",hage ~ "Age du CM",hmstat ~ "Situation matrimoniale",heduc ~ "Niveau d'education",hdiploma ~ "diplome le plus élévé"),statistic = list(hage ~ "{mean} ({sd})"),
                   digits = list(hage ~ 2), 
                   #digits = everything()~c(0,0,0)                   
                   missing = "always",
                   missing_text = "valeurs manquantes") %>% modify_header(label="Caractéristiques du CM")  %>% add_n()
```
